In [1]:
import numpy as np

# Creating a 2D Array
array_2d = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("2D Array:")
print(array_2d)

# Creating a 3D Array
array_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("3D Array:")
print(array_3d)

# Basic Operations
print("Addition:")
print(array_2d + 5)

print("Subtraction:")
print(array_2d - 5)

print("Multiplication:")
print(array_2d * 2)

print("Division:")
print(array_2d / 10)

# Matrix Operations
print("Transpose:")
print(array_2d.T)

print("Sum:")
print(np.sum(array_2d))

print("Mean:")
print(np.mean(array_2d))

print("Maximum:")
print(np.max(array_2d))

print("Minimum:")
print(np.min(array_2d))

# Accessing Elements
print("Element at Row 2, Column 3:")
print(array_2d[1][2])

print("First Matrix in 3D Array:")
print(array_3d[0])

print("Element 11 from 3D Array:")
print(array_3d[1][1][1])

# Reshape
reshaped = array_2d.reshape(3, 2)

print("Reshaped Array:")
print(reshaped)

# Flatten
print("Flattened Array:")
print(array_2d.flatten())

2D Array:
[[10 20 30]
 [40 50 60]]
3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Addition:
[[15 25 35]
 [45 55 65]]
Subtraction:
[[ 5 15 25]
 [35 45 55]]
Multiplication:
[[ 20  40  60]
 [ 80 100 120]]
Division:
[[1. 2. 3.]
 [4. 5. 6.]]
Transpose:
[[10 40]
 [20 50]
 [30 60]]
Sum:
210
Mean:
35.0
Maximum:
60
Minimum:
10
Element at Row 2, Column 3:
60
First Matrix in 3D Array:
[[1 2 3]
 [4 5 6]]
Element 11 from 3D Array:
11
Reshaped Array:
[[10 20]
 [30 40]
 [50 60]]
Flattened Array:
[10 20 30 40 50 60]
