In [5]:
import numpy as np

#creating a arrray
arr=np.array([[1,2,3,4,4],
             [1,2,3,4,4]])
print(arr)
print(arr.ndim)
print(arr.shape)
a=np.arange(0,10)       #to add elements in a list
print(a)

[[1 2 3 4 4]
 [1 2 3 4 4]]
2
(2, 5)
[0 1 2 3 4 5 6 7 8 9]


In [6]:
arr= np.linspace(1,10,5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [37]:
arr=np.logspace(1,3,3)
arr

array([  10.,  100., 1000.])

In [50]:
arr= np.zeros(6)
print(arr)
arr=np.zeros([2,3,4])
print(arr)

[0. 0. 0. 0. 0. 0.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [51]:
arr= np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr= np.full(10,2)
print(arr)
arr= np.full([4,3],7)
print(arr)

[2 2 2 2 2 2 2 2 2 2]
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [8]:
arr= np.empty([2,3]) #uninitialized
arr

array([[ 1.79769313e+308, -1.79769313e+308,  2.00000000e+000],
       [ 2.22044605e-016,  2.22507386e-308,  4.94065646e-324]])

In [77]:
arr= np.random.rand(10)
print(arr)
arr= np.random.rand(2,3)
print(arr)
arr=np.random.randint(10,100)#random int generator
print(arr)
arr=np.random.randint(10,100,[2,3])#random int generator
print(arr)

[0.95390121 0.53051553 0.61295023 0.225426   0.58957563 0.76184735
 0.44169979 0.21245322 0.41903002 0.02635102]
[[0.76838385 0.0744082  0.83374793]
 [0.30052415 0.64744856 0.52714595]]
90
[[26 69 64]
 [17 29 10]]
