In [2]:
import numpy as np

# Creating NumPy arrays
numbers = np.array([10, 20, 30, 40, 50])

print("Original Array:")
print(numbers)

# Accessing elements
print("First element:")
print(numbers[0])

print("Last element:")
print(numbers[-1])

# Array operations
print("Addition with 5:")
print(numbers + 5)

print("Multiplication by 2:")
print(numbers * 2)

# Finding properties
print("Array size:")
print(numbers.size)

print("Array datatype:")
print(numbers.dtype)



Original Array:
[10 20 30 40 50]

First element:
10

Last element:
50

Addition with 5:
[15 25 35 45 55]

Multiplication by 2:
[ 20  40  60  80 100]

Array size:
5

Array datatype:
int64

Minimum value:
1
